version: '3'
services:
  # Apache web server
  httpd:
    image: httpd
    # Map 8080 to default HTTP port
    ports:
      - 8080:80
    # Map this directory to Apache's htdocs folder
    volumes:
      - .:/usr/local/apache2/htdocs/
  # Google tool for monitoring system and Docker containers
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    # Avoid overlap with Apache web server
    ports:
      - 8081:8080
    # Hooks into system processes
    volumes:
      - /:/rootfs:ro 
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro